### PR TITLE
Removed previous styles and installed TailwindCSS

### PR DESCRIPTION
**Pull request by mikeyxx**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

I installed Tailwind CSS and removed most of the old css styles we had on the application. I also changed the background for the homepage.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### After

new

## Testing Steps / QA Criteria

You may need to do` npm ci` to install dependencies after doing a `git pull origin tailwind`

### CODE REVIEW

**Comment by KarenJParker77** [comment]
Thanks Mike. I'm happy for this to be merged ☺️

**Review by smguerra — APPROVED** [review]
Hi Mike, thanks for the changes, please fell free to go ahead and merge 👍

**Review by cassie202 — COMMENTED** [review]
What do you think about background-color: #F8998B;
check slack for the picture

**Comment by mikeyxx** [comment]
Saw it. I think it looks great.

Also anyone can go ahead and merge to main. I’m currently not on my
computer. So you guys can start working on your parts💪🏽

**Pull request merged**
