### PR TITLE
Item details

### LINKED ISSUE #12: 12. As a user, I want to view a list of my shopping list items in order of how soon I am likely to need to buy each of them again so that it’s clear what I need to buy soon.
## Summary
Sorting items by how soon the user might need to buy them will make it easier for the user to identify what they need to buy, which will in turn help them better plan their shopping trips. To that end, we will be sorting items into 4 possible groups, according to how urgently the user should buy the item:

1. Need to buy soon (7 days or fewer until the next purchase)
2. Need to buy kind of soon (between 7 & 30 days until the next purchase)
3. Need to buy not soon (30 days or more until the next purchase)
4. Inactive (60 days have passed since the last purchase)

To implement this feature, your team will need to create some new UI elements so the user knows how their items are sorted and write some logic behind-the-scenes to perform the sorting itself. Read the acceptance criteria and our notes carefully to be sure you understand the tasks at hand, and don’t be afraid to reach out to the rest of your team, and your mentors if you need help. You’ve got this! 

## Acceptance criteria
- [ ] Items in the list are shown with an indicator that tells the user they should buy the item “soon”, “kind of soon”, or “not soon”; or that the item is “inactive”
	- [ ] This urgency indicator *does not* rely on only color
- [ ] `api/firestore.js` exports a new `comparePurchaseUrgency` function with the following behaviors
	- [ ] sorts inactive items last, then
	- [ ] sorts items in ascending order of days until purchase, and
	- [ ] sorts items with the same days until purchase alphabetically

### A stretch goal
If you complete all of the previous acceptance criteria, consider what happens when an item’s `dateNextPurchased` has passed, but it isn’t yet inactive. Let’s call that item “overdue”.

- [ ] Extend the functionality of `comparePurchaseUrgency` to sort “overdue” items to the top of the list
- [ ] Indicate in your UI when an item is overdue

## Notes
There's a lot to do for this issue! Read this section for some ideas about how to approach the tasks ahead. The `getDaysBetweenDates` function in `src/utils/dates.js` will be useful!

Remember: The dates in the Firestore database are special `Timestamp` objects. You’ll need to call their `toDate()` method to get a JavaScript Date that we can work with.

### Indicating purchase urgency in the UI
It’s tempting to use colors or icons to indicate how soon the user should buy an item. Keep in mind:
- If you use only color, a colorblind user won’t be able to tell the difference between urgency indicators
- If you use icons, you have to teach users what those icons mean

With these constraints, it’s probably best to render plain text, like “soon”, “kind of soon”, etc. in order to show urgency. You can still use color alongside that text, and the design of where that text goes is up to you!

### Sorting the list
We’re sorting by multiple criteria:
1. Whether the item is active or inactive, then
2. By the number of days until its `dateNextPurchased`, and
3. Alphabetically by name, if they have the same number of days until purchase

Sorting by multiple criteria can be tricky! Refer to the MDN docs for [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) and refresh yourself on how to write *compare functions* so you can write the `comparePurchaseUrgency` function.

### PR DESCRIPTION
**Pull request by smguerra**
## Description

This PR adds a new feature that allows users to view detailed information about an item when they click on its name. The item details view/page displays an image, the item name, the number of purchases, and the dates of the last and next purchases.

## Changes Made:

* Implemented the functionality to fetch item data and display it in the item details component.
* Added an image, item name, total purchases, date last purchased, and date next purchased in the item details view.
* Styled the item details page using Tailwind CSS, making it responsive and visually appealing.

## Additional Notes:

* Utilized the differenceInDays method and converted Firebase dates to JavaScript dates using the toDate() method for calculating the difference in days.
* Ensured that the existing functionality of the application was not affected by the new feature.
* Tested the new feature across different scenarios and screen sizes to ensure responsiveness and functionality.

## Related Issue

closes #18

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria

* In your terminal, pull this branch down with the command `git pull origin item-details` and switch to the branch with `git checkout item-details` 
* run `npm ci` to stay up to date 
* Create a new list and add items to it or open and existing List
* Click on one of the item names to navigate to the item detail view/page.
* On the item detail page, check if the image is displayed at the top, followed by the item name, with the first capital letter, total purchases, date last purchased, and date next purchased. Ensure that the information matches the item you selected. 
* Return to the list view from the item details view by utilizing the browser's back button or or by clicking the back button provided.

### CODE REVIEW

**Comment by smguerra** [comment]
Hi Mike, : )  I have created the PR for the Stretch Goal: Add an item details page, the Back to List link's colour wont be approriate for accessibility purposes but I will change it later for any other colour and add a hover state,  when we have the rest of the links and/or button colours defined. Many thanks

**Comment by KarenJParker77** [comment]
Hi Sandra. I know you didn't request my review 😄 but as I won't be available after today I wanted to check it out! It looks really great - well done

**Comment by smguerra** [comment]
Hi Karen, 😊😊 😀, I was thinking to add everyone for review after all changes have been made, but many thanks for your comment,👍🙏

**Comment by mikeyxx** [comment]
This came out really nice🤩 Well done Sandra. See you are becoming a pro already!!🚀🚀

**Pull request closed without merging**
